version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-backend.prod
    image: django
    volumes:
      - $PWD:/app
    networks:
      - backend
      - frontend
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks: 
      - backend
    env_file: bachelorthesis_v2/.env.db

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test1234
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - backend

  client:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile.prod
    image: vue
    volumes:
      - './frontend/:/app'
    networks: 
      - frontend
    ports:
      - 80:80
    environment:
      - NODE_ENV=

networks:
  backend:
  frontend:

volumes:
  postgres_data:
  pgadmin: