# Generated by Django 3.2.13 on 2022-04-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20220421_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_song_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_song_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
