# Generated by Django 3.2.13 on 2022-04-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_auto_20220425_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_profile_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
