# Generated by Django 3.2.13 on 2022-04-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0006_auto_20220426_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
