# Generated by Django 3.2.13 on 2022-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0010_auto_20220504_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_podcast',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
